name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 13:05AM UTC
    - cron: '5 13 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_EDITORS: "False"
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          LOCALE: "pt_BR"
          SYMBOL_VERSION: "3"